### PR TITLE
fixed N(t) plots

### PR DESCRIPTION
**Pull request by andrewkern**
as pointed out in this week's call, the N(t) plotting needed fixing up. This PR patches that.  

Running the plotting code on sims/inferences specified by `tiny_config.yaml` yields the following, which looks reasonable to me, given how rough the `tiny` settings are

image

### CODE REVIEW

**Comment by andrewkern** [comment]
@lntran26, you would be a perfect person to review this!

**Comment by lntran26** [comment]
Great! I'll check it out! Also, I notice we are not plotting smc++ result here. Related to #50, have we decided to leave out smc++ for this analysis or are we still working on including it?

**Comment by andrewkern** [comment]
we can definitely include it, but let's leave that for a separate PR

**Review by lntran26 — APPROVED** [review]
Confirm that I can run the new code and it works for multiple replicates as well. Shown below are the updated plots for 3 replicates of the Constant and OOF_3G09 models. (My stairway plot has 4 lines instead of 3 but that's probably due to how I ran the inference, not a bug in the plotting code).

all_estimated_Ne_Constant
all_estimated_Ne_OOF

**Pull request merged**
