### PR TITLE
swap msmc for msmc2

### PR DESCRIPTION
**Pull request by chriscrsmith**
Changed very little code. To my understanding msmc2 should work as a drop in replacement for msmc, and msmc-tools seems to work on both outputs. The pipeline ran for me without errors.

Associated with issue https://github.com/popsim-consortium/analysis2/issues/48

### CODE REVIEW

**Comment by andrewkern** [comment]
looks good @chriscrsmith but the github action check is failing. to make it pass go edit these lines to reflect `msmc2` changes in `.github/workflows/dry-run.yml` 

https://github.com/popsim-consortium/analysis2/blob/50c9bc16833a4119f91332a4711811e181a61d79/.github/workflows/dry-run.yml#L31-L38

in truth we should probably change out this action, but let's do that in a separate PR

**Review by andrewkern — CHANGES_REQUESTED** [review]
see above comment

**Comment by chriscrsmith** [comment]
Thanks for pointing me towards that file. I think it passed now.

Pretty cool check!

**Review by andrewkern — APPROVED** [review]
LGTM!

**Comment by andrewkern** [comment]
This ran without issues for me! 🎸

**Pull request merged**
