### PR TITLE
refactoring out code

### PR DESCRIPTION
**Pull request by andrewkern**
PR starting the process of refactoring code out of the Snakefile to tidy things into separate modules. 

Generally we want to end up with a module (i.e. a `*.py` file) which contains all the code for a specific analysis and then import that module into our Snakefile. This draft PR gives an example of that idea using the plotting functions that were in the current workflow

### CODE REVIEW

**Comment by andrewkern** [comment]
btw this PR worked after installing a few external dependencies (see #24) 

@xin-huang when you approve we can merge this and continue to refactor stuff

**Comment by petrelharp** [comment]
I will fix up this PR to account for my recent force-push.

**Comment by andrewkern** [comment]
this is major surgery 👨‍⚕️

**Comment by xin-huang** [comment]
`plots.py` is disappeared, should I open a new pr to add it back?
I tested `plots.py` in my machine, it works.

**Comment by andrewkern** [comment]
oh no!

**Comment by petrelharp** [comment]
Ack, sorry!!!

**Pull request merged**
