### PR TITLE
swap msmc for msmc2

### PR DESCRIPTION
**Pull request by chriscrsmith**
Mostly updated the README for installing software. Changed one line in config file.

### CODE REVIEW

**Comment by chriscrsmith** [comment]
Associated with issue #48

**Comment by andrewkern** [comment]
shoot i missed this! @chriscrsmith can I close this and ask you to do a new PR swapping in msmc2 on my updated workflow over on #60, once we merge that?

**Review by andrewkern — CHANGES_REQUESTED** [review]
hoping to move this over to #60

**Comment by chriscrsmith** [comment]
yes

**Comment by andrewkern** [comment]
okay closing and we can reopen a new PR later today

**Pull request closed without merging**
